(cl:defpackage mongodb_store_msgs-msg
  (:use )
  (:export
   "<INSERT>"
   "INSERT"
   "<MOVEENTRIESACTION>"
   "MOVEENTRIESACTION"
   "<MOVEENTRIESACTIONFEEDBACK>"
   "MOVEENTRIESACTIONFEEDBACK"
   "<MOVEENTRIESACTIONGOAL>"
   "MOVEENTRIESACTIONGOAL"
   "<MOVEENTRIESACTIONRESULT>"
   "MOVEENTRIESACTIONRESULT"
   "<MOVEENTRIESFEEDBACK>"
   "MOVEENTRIESFEEDBACK"
   "<MOVEENTRIESGOAL>"
   "MOVEENTRIESGOAL"
   "<MOVEENTRIESRESULT>"
   "MOVEENTRIESRESULT"
   "<SERIALISEDMESSAGE>"
   "SERIALISEDMESSAGE"
   "<STRINGLIST>"
   "STRINGLIST"
   "<STRINGPAIR>"
   "STRINGPAIR"
   "<STRINGPAIRLIST>"
   "STRINGPAIRLIST"
  ))

