; Auto-generated. Do not edit!


(cl:in-package mongodb_store_msgs-msg)


;//! \htmlinclude MoveEntriesFeedback.msg.html

(cl:defclass <MoveEntriesFeedback> (roslisp-msg-protocol:ros-message)
  ((completed
    :reader completed
    :initarg :completed
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass MoveEntriesFeedback (<MoveEntriesFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveEntriesFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveEntriesFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mongodb_store_msgs-msg:<MoveEntriesFeedback> is deprecated: use mongodb_store_msgs-msg:MoveEntriesFeedback instead.")))

(cl:ensure-generic-function 'completed-val :lambda-list '(m))
(cl:defmethod completed-val ((m <MoveEntriesFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mongodb_store_msgs-msg:completed-val is deprecated.  Use mongodb_store_msgs-msg:completed instead.")
  (completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveEntriesFeedback>) ostream)
  "Serializes a message object of type '<MoveEntriesFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'completed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'completed))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveEntriesFeedback>) istream)
  "Deserializes a message object of type '<MoveEntriesFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'completed) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'completed)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveEntriesFeedback>)))
  "Returns string type for a message object of type '<MoveEntriesFeedback>"
  "mongodb_store_msgs/MoveEntriesFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveEntriesFeedback)))
  "Returns string type for a message object of type 'MoveEntriesFeedback"
  "mongodb_store_msgs/MoveEntriesFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveEntriesFeedback>)))
  "Returns md5sum for a message object of type '<MoveEntriesFeedback>"
  "a62bad29223cd7da9d6f04397aee5b94")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveEntriesFeedback)))
  "Returns md5sum for a message object of type 'MoveEntriesFeedback"
  "a62bad29223cd7da9d6f04397aee5b94")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveEntriesFeedback>)))
  "Returns full string definition for message of type '<MoveEntriesFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# the collections which have been operated on so far~%string[] completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveEntriesFeedback)))
  "Returns full string definition for message of type 'MoveEntriesFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# the collections which have been operated on so far~%string[] completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveEntriesFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'completed) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveEntriesFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveEntriesFeedback
    (cl:cons ':completed (completed msg))
))
