// Generated by gencpp from file mongodb_store_msgs/MongoQuerywithProjectionMsg.msg
// DO NOT EDIT!


#ifndef MONGODB_STORE_MSGS_MESSAGE_MONGOQUERYWITHPROJECTIONMSG_H
#define MONGODB_STORE_MSGS_MESSAGE_MONGOQUERYWITHPROJECTIONMSG_H

#include <ros/service_traits.h>


#include <mongodb_store_msgs/MongoQuerywithProjectionMsgRequest.h>
#include <mongodb_store_msgs/MongoQuerywithProjectionMsgResponse.h>


namespace mongodb_store_msgs
{

struct MongoQuerywithProjectionMsg
{

typedef MongoQuerywithProjectionMsgRequest Request;
typedef MongoQuerywithProjectionMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MongoQuerywithProjectionMsg
} // namespace mongodb_store_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsg > {
  static const char* value()
  {
    return "45d9c9b353113ab0888f363d63903883";
  }

  static const char* value(const ::mongodb_store_msgs::MongoQuerywithProjectionMsg&) { return value(); }
};

template<>
struct DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsg > {
  static const char* value()
  {
    return "mongodb_store_msgs/MongoQuerywithProjectionMsg";
  }

  static const char* value(const ::mongodb_store_msgs::MongoQuerywithProjectionMsg&) { return value(); }
};


// service_traits::MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsgRequest> should match 
// service_traits::MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsg > 
template<>
struct MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsg >::value();
  }
  static const char* value(const ::mongodb_store_msgs::MongoQuerywithProjectionMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsgRequest> should match 
// service_traits::DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsg > 
template<>
struct DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsgRequest>
{
  static const char* value()
  {
    return DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsg >::value();
  }
  static const char* value(const ::mongodb_store_msgs::MongoQuerywithProjectionMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsgResponse> should match 
// service_traits::MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsg > 
template<>
struct MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mongodb_store_msgs::MongoQuerywithProjectionMsg >::value();
  }
  static const char* value(const ::mongodb_store_msgs::MongoQuerywithProjectionMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsgResponse> should match 
// service_traits::DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsg > 
template<>
struct DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsgResponse>
{
  static const char* value()
  {
    return DataType< ::mongodb_store_msgs::MongoQuerywithProjectionMsg >::value();
  }
  static const char* value(const ::mongodb_store_msgs::MongoQuerywithProjectionMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MONGODB_STORE_MSGS_MESSAGE_MONGOQUERYWITHPROJECTIONMSG_H
