// Generated by gencpp from file mongodb_store_msgs/MoveEntriesGoal.msg
// DO NOT EDIT!


#ifndef MONGODB_STORE_MSGS_MESSAGE_MOVEENTRIESGOAL_H
#define MONGODB_STORE_MSGS_MESSAGE_MOVEENTRIESGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mongodb_store_msgs/StringList.h>
#include <mongodb_store_msgs/StringPairList.h>

namespace mongodb_store_msgs
{
template <class ContainerAllocator>
struct MoveEntriesGoal_
{
  typedef MoveEntriesGoal_<ContainerAllocator> Type;

  MoveEntriesGoal_()
    : database()
    , collections()
    , move_before()
    , delete_after_move(false)
    , query()  {
    }
  MoveEntriesGoal_(const ContainerAllocator& _alloc)
    : database(_alloc)
    , collections(_alloc)
    , move_before()
    , delete_after_move(false)
    , query(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _database_type;
  _database_type database;

   typedef  ::mongodb_store_msgs::StringList_<ContainerAllocator>  _collections_type;
  _collections_type collections;

   typedef ros::Duration _move_before_type;
  _move_before_type move_before;

   typedef uint8_t _delete_after_move_type;
  _delete_after_move_type delete_after_move;

   typedef  ::mongodb_store_msgs::StringPairList_<ContainerAllocator>  _query_type;
  _query_type query;





  typedef boost::shared_ptr< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveEntriesGoal_

typedef ::mongodb_store_msgs::MoveEntriesGoal_<std::allocator<void> > MoveEntriesGoal;

typedef boost::shared_ptr< ::mongodb_store_msgs::MoveEntriesGoal > MoveEntriesGoalPtr;
typedef boost::shared_ptr< ::mongodb_store_msgs::MoveEntriesGoal const> MoveEntriesGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mongodb_store_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'mongodb_store_msgs': ['/home/vsarathy/proj/tools_sandbox/ros_packages/ros_macgyver/src/mongodb_store/mongodb_store_msgs/msg', '/home/vsarathy/proj/tools_sandbox/ros_packages/ros_macgyver/devel/.private/mongodb_store_msgs/share/mongodb_store_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48aa6e70c15714ce3dfa1b8f64da4ec6";
  }

  static const char* value(const ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48aa6e70c15714ceULL;
  static const uint64_t static_value2 = 0x3dfa1b8f64da4ec6ULL;
};

template<class ContainerAllocator>
struct DataType< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mongodb_store_msgs/MoveEntriesGoal";
  }

  static const char* value(const ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# the db to move entries from\n\
string database\n\
# the collections to move entries from\n\
StringList collections\n\
# only entries before rospy.get_rostime() - move_before are moved. if 0, all are moved\n\
duration move_before\n\
# delete moved entries after replication\n\
bool delete_after_move\n\
# query to move entries by\n\
StringPairList query\n\
\n\
================================================================================\n\
MSG: mongodb_store_msgs/StringList\n\
string[] data\n\
\n\
================================================================================\n\
MSG: mongodb_store_msgs/StringPairList\n\
StringPair[] pairs\n\
\n\
================================================================================\n\
MSG: mongodb_store_msgs/StringPair\n\
string first\n\
string second\n\
";
  }

  static const char* value(const ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.database);
      stream.next(m.collections);
      stream.next(m.move_before);
      stream.next(m.delete_after_move);
      stream.next(m.query);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveEntriesGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mongodb_store_msgs::MoveEntriesGoal_<ContainerAllocator>& v)
  {
    s << indent << "database: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.database);
    s << indent << "collections: ";
    s << std::endl;
    Printer< ::mongodb_store_msgs::StringList_<ContainerAllocator> >::stream(s, indent + "  ", v.collections);
    s << indent << "move_before: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.move_before);
    s << indent << "delete_after_move: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.delete_after_move);
    s << indent << "query: ";
    s << std::endl;
    Printer< ::mongodb_store_msgs::StringPairList_<ContainerAllocator> >::stream(s, indent + "  ", v.query);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MONGODB_STORE_MSGS_MESSAGE_MOVEENTRIESGOAL_H
